"use strict";

var gc = {
    
    ACTION_CODE_HARVEST : 'harvest',
    ACTION_CODE_TRANSFER : 'transfer',
    
    ROOM_NUMBER_1 : 'E51N4',
    
    DEFAULT_CREEP_WORKER: {
        1 : [WORK,CARRY,MOVE],
        2 : [WORK,WORK,CARRY,CARRY,MOVE,MOVE],
        3 : [],
        4 : [],
        5 : [WORK,WORK,WORK,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
        6 : [WORK,WORK,WORK,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
        7 : [WORK,WORK,WORK,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
        8 : [WORK,WORK,WORK,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE]
    },
    
    DEFAULT_CREEP_REPAIRER: {
        1 : [],
        2 : [],
        3 : [],
        4 : [],
        5 : [WORK,WORK,WORK,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
        6 : [WORK,WORK,WORK,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
        7 : [WORK,WORK,WORK,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
        8 : [WORK,WORK,WORK,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
    },
    
    DEFAULT_CREEP_HARVESTER: {
        1 : [],
        2 : [],
        3 : [],
        4 : [],
        5 : [WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
        6 : [WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
        7 : [WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
        8 : [WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE]
    },
    
    DEFAULT_CREEP_PROTECTOR: {
        1 : [],
        2 : [],
        3 : [],
        4 : [],
        5 : [TOUGH,TOUGH,MOVE,ATTACK, RANGED_ATTACK,RANGED_ATTACK,ATTACK, ATTACK, MOVE, MOVE],
        6 : [TOUGH,TOUGH,MOVE,ATTACK, RANGED_ATTACK,RANGED_ATTACK,ATTACK, ATTACK, MOVE, MOVE],
        7 : [TOUGH,TOUGH,MOVE,ATTACK, RANGED_ATTACK,RANGED_ATTACK,ATTACK, ATTACK, MOVE, MOVE],
        8 : [TOUGH,TOUGH,MOVE,ATTACK, RANGED_ATTACK,RANGED_ATTACK,ATTACK, ATTACK, MOVE, MOVE]
    },
        
    DEFAULT_LINK_TRANSFER: {
        5 : [CARRY,CARRY,MOVE,MOVE],
        6 : [CARRY,CARRY,MOVE,MOVE],
        7 : [CARRY,CARRY,MOVE,MOVE],
        8 : [CARRY,CARRY,MOVE,MOVE]
    },
        
    DEFAULT_LINK_UPGRADE: {
        5 : [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
        6 : [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
        7 : [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
        8 : [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE]
    },
        
    DEFAULT_RESOURCE_COLLECTOR : {
        1 : [],
        2 : [],
        3 : [],
        4 : [],
        5 : [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
        6 : [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
        7 : [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
        8 : [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE]
    },
    
    ROLE_HARVESTER : 'harvester',
    ROLE_UPGRADER : 'upgrader',
    ROLE_BUILDER : 'builder',
    ROLE_PROTECTOR : 'protector', 
    ROLE_REPAIRER_WALL : 'repairer.wall', 
    ROLE_REPAIRER_ROAD : 'repairer.road',
    ROLE_STORETOLINK : 'storetolink',
    ROLE_LINKTOUPGRADE : 'linktoupgrade',
    ROLE_RESOURCECOLLECTOR : 'resourcecollector',
        
    ROOM_NUMBER : 'E51N4',
    
    SPAWN_NAME : {
        'E51N4' : 'Yellow',
        'E51N3' : 'Red'
    },
        
    TOWER_ID_1 : '58ffa69fea98794b69733489',
    TOWER_ID_2 : '59073e6d00d2e8d72725196d',
    
    LINK_ID_1 : '59071b01552be4356865779e',
    LINK_ID_2 : '5907032fc953ae8d221f88e8'
}

module.exports = gc;
